### ISSUE TITLE
enabling jwt auth is not working

### ISSUE THREAD

**Issue by SDAdham** [jitsi-contrib/jitsi-kubernetes#12]
I'm not sure what am I missing here:
Based: https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-docker#jitsi-meet-web-configuration
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: jitsi
  name: jitsi
  namespace: jitsi
spec:
  template:
    metadata:
      labels:
        k8s-app: jitsi
    spec:
      containers:
        - name: web
          env:
            - name: PUBLIC_URL
              value: "https://jitsi.example.com"
            - name: ENABLE_AUTH
              value: '1'
            - name: ENABLE_GUESTS
              value: '0'
            - name: AUTH_TYPE
              value: 'jwt'
            - name: JWT_APP_ID
              value: '<app-id>'
            - name: JWT_APP_SECRET
              value: '<secret>'
            - name: JWT_ALLOW_EMPTY
              value: '0'

        - name: prosody
          env:
            - name: PUBLIC_URL
              value: "https://jitsi.example.com"
            - name: ENABLE_AUTH
              value: '1'
            - name: ENABLE_GUESTS
              value: '0'
            - name: AUTH_TYPE
              value: 'jwt'
            - name: JWT_APP_ID
              value: '<app-id>'
            - name: JWT_APP_SECRET
              value: '<secret>'
            - name: JWT_ALLOW_EMPTY
              value: '0'
```
