### ISSUE TITLE
error: accumulating resources

### ISSUE THREAD

**Issue by OverwhelmedStudent** [jitsi-contrib/jitsi-kubernetes#19]
I went through the steps to deploy Jitsi on my microk8s cluster with kustomize and recieve following error:

`error: accumulating resources: accumulation err='accumulating resources from 'https://github.com/jitsi-contrib/jitsi-kubernetes/tree/main/doc/kustomize': yaml: line 218: mapping values are not allowed in this context': evalsymlink failure on '/tmp/kustomize-2873540753/tree/main/doc/kustomize' : lstat /tmp/kustomize-2873540753/tree: no such file or directory`

What have I done wrong?

The plan is to run jitsi on a internal server and access the Service with the IP, without exposing anything to the internet, so a https certificate by letsencrypt is not required or relevant for us. 

I enabled the Ingress microk8s addon and created the .yaml files like this:

010-deployment.yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: jitsi
  name: jitsi
  namespace: jitsi	   
spec:
  template:
    metadata:
      labels:
        k8s-app: jitsi
    spec:
      containers:
        - name: web
          env:
            - name: PUBLIC_URL
              value: "http://192.168.1.70"

        - name: prosody
          env:
            - name: PUBLIC_URL
              value: "http://192.168.1.70"
```
041-ingress.yaml
```
---
###################################################
# Ingress
###################################################
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: jitsi
  namespace: jitsi
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - 192.168.1.70
    secretName: tls-jitsi
  rules:
  - host: 192.168.1.70
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: web
            port:
              number: 80

```
kustomization.yaml
```
namespace: jitsi
bases:
- https://github.com/jitsi-contrib/jitsi-kubernetes/tree/main/doc/kustomize

resources:
- 041-ingress.yaml

patchesStrategicMerge:
- 010-deployment.yaml
```

Thank you for your help!
