### ISSUE TITLE
Cannot have more than 2 users connected

### ISSUE THREAD

**Issue by chazapp** [jitsi-contrib/jitsi-kubernetes#8]
Hi, i'm trying to use this project to deploy Jitsi to my AWS Kubernetes Cluster. Whenever I add 3 or more clients to a room, every other webcam goes black and no sound is working anymore. 
Here's my installation so far: 
`$cat 041-ingress.yml`
```
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: jitsi
  namespace: jitsi
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
    - host: visio.redacted.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  number: 80
  tls:
  - hosts:
    - visio.redacted.com
    secretName: visio-tls-secret

```
`$ cat 010-deployment.yml`
```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: jitsi
  name: jitsi
  namespace: jitsi
spec:
  template:
    metadata:
      labels:
        k8s-app: jitsi
    spec:
      containers:
        - name: web
          env:
            - name: PUBLIC_URL
              value: "https://visio.redacted.com"
          volumeMounts:
            - name: config
              mountPath: /config/custom-config.js
              subPath: custom-config.js
            - name: config
              mountPath: /config/interface_config.js
              subPath: interface_config.js
            - name: images
              mountPath: /usr/share/jitsi-meet/images/redacted.svg
              subPath: redacted.svg
        - name: prosody
          env:
            - name: PUBLIC_URL
              value: "https://visio.redacted.com"
        - name: jvb
          env:
            - name: PUBLIC_URL
              value: "https://visio.redacted.com"
        - name: jicofo
          env:
            - name: PUBLIC_URL
              value: "https://visio.redacted.com"
      volumes:
        - name: config
          configMap:
            name: jitsi-config
        - name: images
          configMap:
            name: redacted-logo
```
`$ cat kustomization.yml`
```
namespace: jitsi
bases:
- https://github.com/jitsi-contrib/kubernetes/doc/kustomize

resources:
- 041-ingress.yml

patchesStrategicMerge:
- 010-deployment.yml

configMapGenerator:
  - name: jitsi-config
    files:
      - custom-config.js
      - interface_config.js
  - name: redacted-logo
    files:
      - redacted.svg
```

I've allowed port 10000 for 0.0.0.0/32 to the cluster AWS Security Groups. I suspect this issue has to do with the absence of ingress/services to port 10000: 

```
$ kubectl get svc -n jitsi
NAME      TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)           AGE
jvb-udp   NodePort    10.100.144.41   <none>        30300:30300/UDP   13d
web       ClusterIP   10.100.28.75    <none>        80/TCP,443/TCP    13d
$ kubectl get ingress -n jitsi 
NAME    CLASS    HOSTS                 ADDRESS                                                    PORTS     AGE
jitsi   <none>   visio.redacted.com   a02d4fredacted151-1096927691.eu-west-3.elb.amazonaws.com   80, 443   13d
```  
Any idea how to amend this configuration in order to have more than 2 clients connected simulatneously ?
Thanks !
